version: 0.0
os: linux
file_exists_behavior: OVERWRITE
files:
  - source: /
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: scripts/restart_nginx.sh
      timeout: 300
  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
